### ISSUE TITLE
Performance/Sum not autocorrecting injects or reduces with blocks

### ISSUE THREAD

**Issue by jmkoni** [rubocop-hq/rubocop-performance#171]
## Expected behavior

After enabling [`Performance/Sum`](https://github.com/rubocop-hq/rubocop-performance/pull/137), I expect that the following lines will all be autocorrected to use `sum`:

```
[1, 2, 3].inject(:+)
[1, 2, 3].reduce(10, :+)
[1, 2, 3].reduce { |acc, elem| acc + elem }
```

## Actual behavior

It only autocorrects the second line:
```
[1, 2, 3].inject(:+)
[1, 2, 3].sum(10)
[1, 2, 3].reduce { |acc, elem| acc + elem }
```

## Steps to reproduce the problem
1. Create a test file with those lines.
2. Run `rubocop -A`
OR
You can replicate this bug by pulling down [this project](https://github.com/jmkoni/rubocop-sum-test), doing a `bundle install`, and running `rubocop -A` 

## RuboCop version

```
rubocop -V
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.7.0 x86_64-darwin19)
```

**Comment by jmkoni** [comment]
`[1,2,3].reduce(:+)` also doesn't autocorrect

**Comment by fatkodima** [comment]
This is an expected behavior, example - https://github.com/rubocop-hq/rubocop-performance/blob/368b748d1c6df62002f2a1b58e4258100e693841/spec/rubocop/cop/performance/sum_spec.rb#L73-L80

We cannot autocorrect when initial value is not given, because we do not know array item types. 
For example, if we try to autocorrect `arr.inject(:+)` to `arr.sum`, where `arr = ['foo', 'bar']`, then this will produce an error, because it should be autocorrected to `arr.sum('')`.

**Comment by fatkodima** [comment]
Or we can autocorrect, but mark this cop as unsafe.

**Comment by jmkoni** [comment]
Somehow I was not notified on these updates. Thank you for the clarification.
