### ISSUE TITLE
Performance/FlatMap does not mark the use of `flatten` without params as an offense

### ISSUE THREAD

**Issue by vzamanillo** [rubocop-hq/rubocop-performance#83]
## Expected behavior

Given a test file test.rb:

```
# frozen_string_literal: true

# 1.
p [1, 2, 3].map(&:digits).flatten(1)

# 2.
p [1, 2, 3].map(&:digits).flatten
```
I would expect RuboCop to suggest flat_map for 1 and 2.

<details>
<summary>Output</summary>

```
Inspecting 1 file
C

Offenses:

test.rb:4:13: C: Performance/FlatMap: Use flat_map instead of map...flatten.
p [1, 2, 3].map(&:digits).flatten(1)
            ^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:7:13: C: Performance/FlatMap: Use flat_map instead of map...flatten.
p [1, 2, 3].map(&:digits).flatten
            ^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```
</details>

## Actual behavior

RuboCop only suggests flat_map for 1.

<details>
<summary>Output</summary>

```
Inspecting 1 file
C

Offenses:

test.rb:4:13: C: Performance/FlatMap: Use flat_map instead of map...flatten.
p [1, 2, 3].map(&:digits).flatten(1)
            ^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected

```
</details>

## Steps to reproduce the problem

Run `rubocop -C false test.rb`

## RuboCop version

```
rubocop -V
0.76.0 (using Parser 2.6.2.1, running on ruby 2.3.1 x86_64-linux)
```

**Comment by pocke** [comment]
It is the expected behavior. Because `flatten(1)` and `flatten` has a different meaning. We can confirm it with a nested array.

```ruby
[1, 2, 3].map { |x| [x, [x]] }.flatten # => [1, 1, 2, 2, 3, 3]
[1, 2, 3].map { |x| [x, [x]] }.flatten(1) # => [1, [1], 2, [2], 3, [3]]
```


And `flat_map` works like `flatten(1)`. So the cop only warns about `flatten(1)` by default.

```ruby
[1, 2, 3].flat_map { |x| [x, [x]] } # => [1, [1], 2, [2], 3, [3]]
```



But you can configure the cop with `EnabledForFlattenWithoutParams: true` to enable an offense for `flatten` without argument.


https://github.com/rubocop-hq/rubocop-performance/blob/master/manual/cops_performance.md#configurable-attributes-3

**Comment by vzamanillo** [comment]
Thank you pocke.
